/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaldoRouteImport } from './routes/saldo'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as KalkulatorRouteImport } from './routes/kalkulator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PiutangIndexRouteImport } from './routes/piutang.index'
import { Route as BazarIndexRouteImport } from './routes/bazar.index'
import { Route as PiutangCustomerRouteImport } from './routes/piutang.$customer'
import { Route as BazarIdRouteImport } from './routes/bazar.$id'
import { Route as BazarIdRekapanRouteImport } from './routes/bazar.$id.rekapan'

const SaldoRoute = SaldoRouteImport.update({
  id: '/saldo',
  path: '/saldo',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const KalkulatorRoute = KalkulatorRouteImport.update({
  id: '/kalkulator',
  path: '/kalkulator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PiutangIndexRoute = PiutangIndexRouteImport.update({
  id: '/piutang/',
  path: '/piutang/',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarIndexRoute = BazarIndexRouteImport.update({
  id: '/bazar/',
  path: '/bazar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PiutangCustomerRoute = PiutangCustomerRouteImport.update({
  id: '/piutang/$customer',
  path: '/piutang/$customer',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarIdRoute = BazarIdRouteImport.update({
  id: '/bazar/$id',
  path: '/bazar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BazarIdRekapanRoute = BazarIdRekapanRouteImport.update({
  id: '/bazar/$id/rekapan',
  path: '/bazar/$id/rekapan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalkulator': typeof KalkulatorRoute
  '/riwayat': typeof RiwayatRoute
  '/saldo': typeof SaldoRoute
  '/bazar/$id': typeof BazarIdRoute
  '/bazar/$id/rekapan': typeof BazarIdRekapanRoute
  '/piutang/$customer': typeof PiutangCustomerRoute
  '/bazar/': typeof BazarIndexRoute
  '/piutang/': typeof PiutangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalkulator': typeof KalkulatorRoute
  '/riwayat': typeof RiwayatRoute
  '/saldo': typeof SaldoRoute
  '/bazar/$id': typeof BazarIdRoute
  '/bazar/$id/rekapan': typeof BazarIdRekapanRoute
  '/piutang/$customer': typeof PiutangCustomerRoute
  '/bazar': typeof BazarIndexRoute
  '/piutang': typeof PiutangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kalkulator': typeof KalkulatorRoute
  '/riwayat': typeof RiwayatRoute
  '/saldo': typeof SaldoRoute
  '/bazar/$id': typeof BazarIdRoute
  '/bazar/$id/rekapan': typeof BazarIdRekapanRoute
  '/piutang/$customer': typeof PiutangCustomerRoute
  '/bazar/': typeof BazarIndexRoute
  '/piutang/': typeof PiutangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/kalkulator'
    | '/riwayat'
    | '/saldo'
    | '/bazar/$id'
    | '/bazar/$id/rekapan'
    | '/piutang/$customer'
    | '/bazar/'
    | '/piutang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kalkulator'
    | '/riwayat'
    | '/saldo'
    | '/bazar/$id'
    | '/bazar/$id/rekapan'
    | '/piutang/$customer'
    | '/bazar'
    | '/piutang'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/kalkulator'
    | '/riwayat'
    | '/saldo'
    | '/bazar/$id'
    | '/bazar/$id/rekapan'
    | '/piutang/$customer'
    | '/bazar/'
    | '/piutang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  KalkulatorRoute: typeof KalkulatorRoute
  RiwayatRoute: typeof RiwayatRoute
  SaldoRoute: typeof SaldoRoute
  BazarIdRoute: typeof BazarIdRoute
  BazarIdRekapanRoute: typeof BazarIdRekapanRoute
  PiutangCustomerRoute: typeof PiutangCustomerRoute
  BazarIndexRoute: typeof BazarIndexRoute
  PiutangIndexRoute: typeof PiutangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saldo': {
      id: '/saldo'
      path: '/saldo'
      fullPath: '/saldo'
      preLoaderRoute: typeof SaldoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kalkulator': {
      id: '/kalkulator'
      path: '/kalkulator'
      fullPath: '/kalkulator'
      preLoaderRoute: typeof KalkulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piutang/': {
      id: '/piutang/'
      path: '/piutang'
      fullPath: '/piutang/'
      preLoaderRoute: typeof PiutangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar/': {
      id: '/bazar/'
      path: '/bazar'
      fullPath: '/bazar/'
      preLoaderRoute: typeof BazarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piutang/$customer': {
      id: '/piutang/$customer'
      path: '/piutang/$customer'
      fullPath: '/piutang/$customer'
      preLoaderRoute: typeof PiutangCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar/$id': {
      id: '/bazar/$id'
      path: '/bazar/$id'
      fullPath: '/bazar/$id'
      preLoaderRoute: typeof BazarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bazar/$id/rekapan': {
      id: '/bazar/$id/rekapan'
      path: '/bazar/$id/rekapan'
      fullPath: '/bazar/$id/rekapan'
      preLoaderRoute: typeof BazarIdRekapanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  KalkulatorRoute: KalkulatorRoute,
  RiwayatRoute: RiwayatRoute,
  SaldoRoute: SaldoRoute,
  BazarIdRoute: BazarIdRoute,
  BazarIdRekapanRoute: BazarIdRekapanRoute,
  PiutangCustomerRoute: PiutangCustomerRoute,
  BazarIndexRoute: BazarIndexRoute,
  PiutangIndexRoute: PiutangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
